### ISSUE TITLE
unable to load XML in WMTS

### ISSUE THREAD

**Issue by ShayanSolution** [Esri/arcgis-runtime-samples-qt#809]
Hi,
I am trying to run WMTS sample. i am using this xml for getCapabilities in below URL:

https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/<your-token>/?
request=getcapabilities&service=wmts
your-token =  172d422a3e65e5010d95ac5fc27eda

When i am using this in browser, its giving me proper xml response,BUT in  app swift code says invalid XML provided (For Ref: find attached Image below)

Please guide about that how to handle "getcapabilities" in Swift for URL because in sample code for JavaScript its Obvious but not clear for Swift Coding.

We are waiting for early response.
Thank You.
![whatsapp image 2018-12-06 at 6 25 47 pm](https://user-images.githubusercontent.com/25619/49587052-af7cef80-f984-11e8-852f-53ced77491ce.jpeg)

**Comment by ldanzinger** [comment]
@ShayanSolution FYI, this repo is for the Qt SDK. The iOS/Swift repo is here - https://github.com/Esri/arcgis-runtime-samples-ios

As for the error you are getting, it seems like your URL might be private and also there are some spaces in it, so it is difficult to know what is happening

**Comment by ShayanSolution** [comment]
@ldanzinger  thanks for your response. URL above is correct i am pasting again here

https://api.lantmateriet.se/open/topowebb-ccby/v1/wmts/token/172d422a3e65e5010d95ac5fc27eda/?request=getcapabilities&service=wmts

Its giving xml in browser successfully but not working for ios

https://github.com/Lantmateriet/Example-consuming-WMTS solutions is already implemented in javascript but we are unable to make it functional in swift 4.0

Your help is highly appreciated.

Thanks

**Comment by anmacdonald** [comment]
Hi @ShayanSolution,

This is what I see:

![image](https://user-images.githubusercontent.com/42203545/49667037-bfaed080-fa51-11e8-8577-d933a2e57248.png)

The link works in the  **Qt C++** sample.

The iOS/Swift team can help you if you write your issue here:
https://github.com/Esri/arcgis-runtime-samples-ios

This repo is for **Qt C++**. I am sorry, we can not help with **Swift**. 

I have closed this issue as it is not related to **Qt C++**.

Wishing you the best of luck,
Archibald
